import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from "@/components/SessionProvider/SessionProvider";
import "./globals.css";
import { getCurrentUser } from "../lib/getCurrentUser";
import { userType } from "../../types/global/UserType";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    user: userType;
  };
}) {
  const user = await getCurrentUser();
  console.log(user);
  if (user) {
    params.user = user;
  }
  return (
    <html lang="fr">
      <body suppressHydrationWarning={true} className={inter.className}>
        <SessionProvider>{children}</SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
