import "../../styles/globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import SessionProvider from "@/components/SessionProvider/SessionProvider";
import { ChakraProvider } from '@chakra-ui/react'

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning={true} lang={"fr"}>
      <body suppressHydrationWarning={true} className={roboto.className}>
        <ChakraProvider>
          <SessionProvider>{children}</SessionProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
